print ("Olá mundo, juntei esse 3 desafios em um só!")
nome=input('Qual seu nome? ')
print(nome, "! Olá é um prazer te conhecer :D")
dia=input('Qual dia você nasceu? ')
mes=input('Qual mês? ')
ano=input('Em qual ano? ')
print("Você nasceu no dia", dia," no mês", mes," no ano", ano," Certo?")
print("Me fale uma conta")
numero_uno=input('Primeiro numero:')
numero_dos=input('Segundo numero:')
print(numero_uno , numero_dos, " AHAHAHHAAH, enganei você so juntei esses numeros :D")
